-- Add all missing Webflow fields to services table
ALTER TABLE services
ADD COLUMN IF NOT EXISTS short_description text,
ADD COLUMN IF NOT EXISTS short_description_en text,
ADD COLUMN IF NOT EXISTS short_description_sv text,
ADD COLUMN IF NOT EXISTS price text,
ADD COLUMN IF NOT EXISTS price_from text,
ADD COLUMN IF NOT EXISTS service_includes text,
ADD COLUMN IF NOT EXISTS service_includes_en text,
ADD COLUMN IF NOT EXISTS service_includes_sv text,
ADD COLUMN IF NOT EXISTS step_1_text text,
ADD COLUMN IF NOT EXISTS step_1_text_en text,
ADD COLUMN IF NOT EXISTS step_1_text_sv text,
ADD COLUMN IF NOT EXISTS step_1_illustration text,
ADD COLUMN IF NOT EXISTS step_2_text text,
ADD COLUMN IF NOT EXISTS step_2_text_en text,
ADD COLUMN IF NOT EXISTS step_2_text_sv text,
ADD COLUMN IF NOT EXISTS step_2_illustration text,
ADD COLUMN IF NOT EXISTS step_3_text text,
ADD COLUMN IF NOT EXISTS step_3_text_en text,
ADD COLUMN IF NOT EXISTS step_3_text_sv text,
ADD COLUMN IF NOT EXISTS step_3_illustration text,
ADD COLUMN IF NOT EXISTS price_first_column text,
ADD COLUMN IF NOT EXISTS price_first_column_en text,
ADD COLUMN IF NOT EXISTS price_first_column_sv text,
ADD COLUMN IF NOT EXISTS price_second_column text,
ADD COLUMN IF NOT EXISTS price_second_column_en text,
ADD COLUMN IF NOT EXISTS price_second_column_sv text,
ADD COLUMN IF NOT EXISTS price_third_column text,
ADD COLUMN IF NOT EXISTS price_third_column_en text,
ADD COLUMN IF NOT EXISTS price_third_column_sv text,
ADD COLUMN IF NOT EXISTS season_product boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS service_type_schema text;